### PR TITLE
Create main.js

### PR DESCRIPTION
**Pull request by Torotv**
you should add a js/

### CODE REVIEW

**Comment by Torotv** [comment]
Main.mkd
#1

**Comment by Nanomotion** [comment]
This project doesn't even use JavaScript.

**Comment by Torotv** [comment]
oh! SOrry!

**Comment by Nanomotion** [comment]
Did you even look at the code??

**Comment by Torotv** [comment]
What Does That Mean?

**Comment by DeveloperTJ** [comment]
It means that there will be no more updates in the future and the project will not be maintained.

**Pull request closed without merging**
